import LocalizedStrings from 'react-localization';

const t = new LocalizedStrings({
  en: {
    login: 'Sign In',
    save: 'Save',
    settings: 'Settings',
    descUserSettings: 'You can change the website language here',
    cancel: 'Cancel',
    create: 'Create',
    logout: 'Logout',
    logoutWarning: 'Are you sure you want to logout?',
    editProfil: 'Edit Your Profile',
    editProfilDesc: 'You can set an avatar!',
    userAvatar: 'User Avatar',
    username: 'Username',
    password: 'Password',
    update: 'Update',
    remove: 'Remove',
    or: 'or',
    textChannels: 'Texts channels',
    editServer: 'Edit Server',
    deleteServer: 'Delete Server',
    createChannel: 'Create Text Channel',
    channelName: 'Channel name',
    createServer: 'Create a server',
    createServerDesc: 'Give your new server a personality with a name and an icon. You can always change it later.',
    serverName: 'Server name',
    joinServer: 'Join a server',
    join: 'Join',
    deleteChannel: 'Delete Channel',
    delete: 'Delete',
    enterServerName: 'Enter server name',
    editTextChannel: 'Edit Text Channel',
    edit: 'Edit',
    editServerDesc: 'You can change the name of your server and set a server avatar!',
    serverAvatar: 'Server Avatar',
    send: 'Send',
  },
  fr: {
    login: 'Connexion',
    save: 'Sauvegarder',
    settings: 'Paramètres',
    descUserSettings: 'Vous pouvez changer la langue du site ici',
    cancel: 'Annuler',
    create: 'Créer',
    logout: 'Se déconnecter',
    logoutWarning: 'Ëtes vous sûr de vouloir vous déconnecter ?',
    editProfil: 'Modifier votre profil',
    editProfilDesc: 'Vous pouvez ajouter un avatar !',
    userAvatar: 'Avatar',
    username: 'Nom d\'utilisateur',
    password: 'Mot de passe',
    update: 'Mettre à jour',
    remove: 'Supprimer',
    or: 'ou',
    textChannels: 'Salons textuels',
    editServer: 'Modifier',
    deleteServer: 'Supprimer',
    createChannel: 'Créer un salon textuel',
    channelName: 'Nom du salon',
    createServer: 'Créer un server',
    createServerDesc: 'Donner à votre nouveau serveur une personnalité avec un nom et une image. Vous pourrez toujours les changer plus tard.',
    serverName: 'Nom du serveur',
    joinServer: 'Rejoindre un serveur',
    join: 'Rejoindre',
    deleteChannel: 'Supprimer le salon',
    delete: 'Supprimer',
    enterServerName: 'Entrer le nom du serveur',
    editTextChannel: 'Modifier le salon textuel',
    edit: 'Modifier',
    editServerDesc: 'Vous pouvez changer le nom du server et l\'image !',
    serverAvatar: 'Image du serveur',
    send: 'Envoyer',
  },
});

export default t;
